Repository ovh-ux/ng-ovh-actions-menu, pull requests merged in 2019-08, with the labels that each got.

#31 docs: update installation documentation
  README.md
Labels: documentation

#35 Bugfix/upgrade dependencies
  package.json
  yarn.lock
Labels: dependencies

#36 Release v5.0.1
  package.json
  yarn.lock
Labels: release

#39 fix(deps): upgrade component-rollup-config to v6.0.2
  package.json
  yarn.lock
Labels: bug, dependencies
